apiVersion: v1
kind: Service
metadata:
  name: {{ template "compute.backend.fullname" $ }}-backend
  labels:
  {{- include "compute.backend.labels" $ | nindent 4 }}
spec:
  selector:
  {{- include "compute.backend.matchLabels" $ | nindent 4 }}
    component/part: backend
  ports:
    - port: 8888
      protocol: TCP
      name: metrics
