{{- if $.Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "compute.backend.fullname" $ }}-backend
  labels:
  {{- include "compute.backend.labels" $ | nindent 4 }}
  {{- toYaml $.Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "compute.backend.matchLabels" $ | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 10s
{{- end }}
