apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "compute.backend.fullname" . }}-backend
data:
  IMAGE: {{ .Values.backend.image }}:{{ .Values.backend.imageTag }}
  IMAGE_PULL_POLICY: {{ .Values.backend.imagePullPolicy }}
  DATA_CLAIM_NAME: {{ .Values.persistence.existingClaim | default (include "compute.fullname" .) }}
  PROVISIONER_BACKEND: {{ template "compute.provisioner.backendService" . }}

  CLIENT_ID: {{ .Values.backend.clientID }}
  CLIENT_SECRET: {{ .Values.backend.clientSecret }}
  TOKEN_URL: {{ .Values.backend.tokenUrl }}
  API_SCHEMA_URL: http://{{ template "compute.wps.fullname" . }}.{{ $.Release.Namespace }}.svc:8000/wps/api/schema/
  DATA_PATH: /data/public
  THREDDS_URL: {{ .Values.threddsUrl }}

  CELERY_BROKER_URL: redis://{{ template "redis.fullname" . }}-master/0
  CELERY_RESULT_BACKEND: redis://{{ template "redis.fullname" . }}-master/0
  
  SCHEDULER_CPU: {{ .Values.userResources.scheduler.resources.limits.cpu | quote }}
  SCHEDULER_MEMORY: {{ .Values.userResources.scheduler.resources.limits.memory | quote }}
  WORKER_NTHREADS: {{ .Values.userResources.worker.nThreads | quote }}
  WORKERS: {{ .Values.userResources.worker.instances | quote }}
  USER_LIMIT_CPU: {{ .Values.userResources.resources.limits.cpu | quote }}
  USER_LIMIT_MEMORY: {{ .Values.userResources.resources.limits.memory | quote }}
  USER_REQUEST_CPU: {{ .Values.userResources.resources.requests.cpu | quote }}
  USER_REQUEST_MEMORY: {{ .Values.userResources.resources.requests.memory | quote }}

  REDIS_HOST: {{ template "redis.fullname" . }}-master.{{ .Release.Namespace }}.svc
  REDIS_PORT: {{ .Values.redis.master.service.port | quote }}
  REDIS_DB: "0"

  PROMETHEUS_PUSHGATEWAY_HOST: {{ template "prometheus-pushgateway.fullname" . }}.{{ .Release.Namespace }}.svc
