apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "compute.celery.fullname" . }}-backend
  labels:
    {{- include "compute.celery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery.backend.replicas }}
  selector:
    matchLabels:
    {{- include "compute.celery.matchLabels" . | nindent 6 }}
      component/part: backend
  template:
    metadata:
      labels:
      {{- include "compute.celery.matchLabels" . | nindent 8 }}
        component/part: backend
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/celery-backend-configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.celery.nodeSelector }}
      nodeSelector: 
      {{ .Values.celery.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
      - name: register
        image: {{ .Values.celery.image }}:{{ .Values.celery.imageTag }}
        imagePullPolicy: {{ .Values.celery.imagePullPolicy }}
        args:
          - /bin/bash
          - -c
          - "until nslookup ${INTERNAL_LB}; do echo 'Waiting'; done; compute-tasks-register"
        resources:
        {{ .Values.celery.backend.resources | toYaml | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ template "compute.celery.fullname" . }}-backend
      containers:
      - name: backend
        image: {{ .Values.celery.image }}:{{ .Values.celery.imageTag }}
        imagePullPolicy: {{ .Values.celery.imagePullPolicy }}
        args:
          - /bin/bash
          - -c
          - "compute-tasks-backend --queue-host ${PROVISIONER_BACKEND}"
        resources:
        {{ .Values.celery.backend.resources | toYaml | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ template "compute.celery.fullname" . }}-backend
        volumeMounts:
        - mountPath: /etc/config
          name: mapping-volume
      {{- range .Values.celery.backend.localMapping.mounts }}
        - name: mapping-{{ .path | toString | sha256sum | substr 0 8}}
          mountPath: {{ .path }}
          readOnly: true
      {{- end }}
      volumes:
      - name: mapping-volume
        configMap:
          name: {{ template "compute.celery.fullname" . }}-mapping
    {{- range .Values.celery.backend.localMapping.mounts }}
      {{- if eq .type "hostpath" }}
      - name: mapping-{{ .path | toString | sha256sum | substr 0 8}}
        hostPath:
          path: {{ .path }}
      {{- end }}
    {{- end }}
