apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "compute.celery.fullname" . }}-worker
  labels:
  {{- include "compute.celery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
    {{- include "compute.celery.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "compute.celery.matchLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ list (include (print .Template.BasePath "/wps-secret.yaml") .) (include (print .Template.BasePath "/celery-backend-configmap.yaml") .) (include (print .Template.BasePath "/celery-mapping-configmap.yaml") .) | join " " | sha256sum }}
      {{- if .Values.celery.annotations }}
      {{- .Values.celery.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.celery.nodeSelector }}
      nodeSelector: 
      {{ .Values.celery.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: metrics
        image: {{ .Values.celery.image }}:{{ .Values.celery.imageTag }}
        imagePullPolicy: {{ .Values.celery.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.celery.metrics.service.port }}
          protocol: TCP
        command:
          - tini
          - --
        args:
          - /bin/bash
          - -c
          - "mkdir -p /metrics && compute-tasks-metrics"
        resources:
        {{ .Values.celery.metrics.resources | toYaml | nindent 10 }}
      - name: worker
        image: {{ .Values.celery.image }}:{{ .Values.celery.imageTag }}
        imagePullPolicy: {{ .Values.celery.imagePullPolicy }}
        command:
          - tini
          - --
        args: 
          - /bin/bash
          - entrypoint.sh
          - "-c"
          - "1"
          - "-Q"
          - "ingress"
          - "-l"
          - "DEBUG"
          - "--max-tasks-per-child"
          - "1"
        livenessProbe:
          exec:
            command:
            - bash
            - /healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - bash
            - /healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        resources: 
        {{ .Values.celery.resources | toYaml | nindent 10 }}
        env:
        - name: PROMETHEUS_HOST
          value: {{ required "Set celery.prometheusUrl" .Values.celery.prometheusUrl }}
        envFrom:
        - secretRef:
            name: {{ template "compute.wps.fullname" . }}
        - configMapRef:
            name: {{ template "compute.celery.fullname" . }}-backend
        volumeMounts:
        - mountPath: /metrics
          name: metrics-volume
        - mountPath: /data/public
          name: data-volume
        - mountPath: /etc/config
          name: mapping-volume
      volumes:
      - name: mapping-volume
        configMap:
          name: {{ template "compute.celery.fullname" . }}-mapping
      - name: metrics-volume
        emptyDir: {}
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.dataClaimName }}
