apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-celery-worker
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
spec:
  replicas: {{ $.Values.celery.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: celery
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/wps-secret.yaml") $ | sha256sum }}
      {{- if $.Values.celery.annotations }}
        {{- $.Values.celery.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
    spec:
      {{- if $.Values.celery.nodeSelector }}
      nodeSelector: 
        {{ $.Values.celery.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- end }}
      {{- if $.Values.celery.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.celery.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" $ }}-celery-worker-metrics
        image: {{ $.Values.celery.image }}:{{ $.Values.celery.imageTag }}
        imagePullPolicy: {{ $.Values.celery.imagePullPolicy }}
        ports:
        - containerPort: {{ $.Values.celery.metrics.service.port }}
          protocol: TCP
        command:
          - tini
          - --
        args:
          - /bin/bash
          - -c
          - "mkdir -p /metrics && compute-tasks-metrics"
        resources:
          {{ $.Values.celery.metrics.resources | toYaml | trimSuffix "\n" | nindent 10 }}
      - name: {{ template "esgf-compute-wps.name" $ }}-celery-worker
        image: {{ $.Values.celery.image }}:{{ $.Values.celery.imageTag }}
        imagePullPolicy: {{ $.Values.celery.imagePullPolicy }}
        {{- if not $.Values.celery.development }}
        command: ["tini", "--"]
        args: 
          - /bin/bash
          - entrypoint.sh
          - "-c"
          - "1"
          - "-Q"
          - "ingress"
          - "-l"
          - "DEBUG"
          - "--max-tasks-per-child"
          - "1"
        {{- end }}
        {{- if $.Values.celery.development }}
        command:
          - tini
          - --
          - sleep
          - infinity
        {{- end }}
        {{- if not $.Values.development }}
        livenessProbe:
          exec:
            command:
            - bash
            - /healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - bash
            - /healthcheck.sh
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        {{- end }}
        resources: {{ $.Values.celery.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        env:
        {{- if $.Values.celery.development }}
        - name: DEV
          value: "1"
        - name: WPS_DEBUG
          value: "1"
        {{- end }}
        - name: PROVISIONER_BACKEND
          value: {{ template "esgf-compute-wps.fullname" $ }}-provisioner.{{ $.Release.Namespace }}.svc:{{ $.Values.provisioner.backendPort }}
        - name: CELERY_BROKER_URL
          value: redis://{{ template "redis.fullname" $ }}-master/0
        - name: CELERY_RESULT_BACKEND
          value: redis://{{ template "redis.fullname" $ }}-master/0
        - name: PROMETHEUS_HOST
          value: {{ required "Set celery.prometheusUrl" $.Values.celery.prometheusUrl }}
        - name: INTERNAL_LB
          value: {{ template "traefik.fullname" $ }}.{{ $.Release.Namespace }}.svc
        - name: API_USERNAME
          value: {{ $.Values.wps.apiUsername }}
        - name: API_PASSWORD
          value: {{ $.Values.wps.apiPassword }}
        - name: NAMESPACE
          value: {{ $.Release.Namespace }}
        - name: DATA_PATH
          value: /data/public
        - name: WORKERS
          value: {{ $.Values.celery.backend.workers | quote }}
        envFrom:
        - secretRef:
            name: {{ template "esgf-compute-wps.fullname" $ }}-wps
        volumeMounts:
        {{- if $.Values.celery.development }}
        - name: devel-volume
          mountPath: /devel
        {{- end }}
        - mountPath: /metrics
          name: metrics-volume
        - mountPath: /data/public
          name: data-volume
          subPath: public
      volumes:
      {{- if or $.Values.celery.development $.Values.celery.backend.development }}
      - name: devel-volume
        hostPath: 
          path: /opt/cwt/devel
          type: DirectoryOrCreate
      {{- end }}
      - name: metrics-volume
        emptyDir: {}
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ $.Values.persistence.dataClaimName | default "data-pvc" }}
