apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "compute.celery.fullname" . }}-backend
data:
  IMAGE: {{ .Values.celery.image }}:{{ .Values.celery.imageTag }}
  # IMAGE_PULL_SECRET: {{ .Values.celery.imagePullSecret }}
  IMAGE_PULL_POLICY: {{ .Values.celery.imagePullPolicy }}
  DATA_CLAIM_NAME: {{ .Values.persistence.dataClaimName }}
  PROVISIONER_BACKEND: {{ template "compute.provisioner.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.provisioner.backendPort }}
  
  API_HOST: {{ template "compute.wps.fullname" . }}.{{ .Release.Namespace }}.svc
  API_URL: http://{{ template "compute.wps.fullname" . }}.{{ .Release.Namespace }}.svc:8000/internal_api/schema
  API_USERNAME: {{ .Values.wps.apiUsername }}
  API_PASSWORD: {{ .Values.wps.apiPassword }}
  DATA_PATH: /data/public

  CELERY_BROKER_URL: redis://{{ template "redis.fullname" . }}-master/0
  CELERY_RESULT_BACKEND: redis://{{ template "redis.fullname" . }}-master/0
  
  SCHEDULER_CPU: {{ .Values.userResources.scheduler.resources.limits.cpu | quote }}
  SCHEDULER_MEMORY: {{ .Values.userResources.scheduler.resources.limits.memory | quote }}
  WORKER_NTHREADS: {{ .Values.userResources.worker.nThreads | quote }}
  WORKERS: {{ .Values.userResources.worker.instances | quote }}
  USER_LIMIT_CPU: {{ .Values.userResources.resources.limits.cpu | quote }}
  USER_LIMIT_MEMORY: {{ .Values.userResources.resources.limits.memory | quote }}
  USER_REQUEST_CPU: {{ .Values.userResources.resources.requests.cpu | quote }}
  USER_REQUEST_MEMORY: {{ .Values.userResources.resources.requests.memory | quote }}

  REDIS_HOST: {{ template "redis.fullname" . }}-master.{{ .Release.Namespace }}.svc
  REDIS_PORT: {{ .Values.redis.master.service.port | quote }}
  REDIS_DB: {{ .Values.celery.backend.redisDB | quote }}

  PROMETHEUS_PUSHGATEWAY_HOST: {{ template "prometheus-pushgateway.fullname" . }}.{{ .Release.Namespace }}.svc
