apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "compute.wps.fullname" . }}
  labels:
{{ .Values.ingressRoute.labels | toYaml | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: PathPrefix(`/wps`)
    kind: Rule
    services:
    - name: {{ include "compute.wps.fullname" . }}
      port: 8000
      kind: Service
  - match: PathPrefix(`/threddsCWT`)
    kind: Rule
    services:
    - name: {{ include "compute.thredds.fullname" . }}
      port: 8080
      kind: Service
