{{- if .Values.nginx.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "compute.nginx.fullname" . }}
  labels:
  {{- include "compute.nginx.labels" . | nindent 4 }}
  {{- if .Values.nginx.ingress.labels }}
  {{ toYaml .Values.nginx.ingress.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.nginx.ingress.annotations }}
  annotations:
  {{ toYaml .Values.nginx.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "compute.nginx.fullname" . }}
              servicePort: 80
{{- end }}
