apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-provisioner
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: provisioner
    spec:
      serviceAccountName: wps
      {{- if .Values.provisioner.nodeSelector }}
      nodeSelector: 
        {{ .Values.provisioner.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- end }}
      {{- if $.Values.provisioner.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.provisioner.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" . }}-provisioner
        image: {{ .Values.provisioner.image }}:{{ .Values.provisioner.imageTag }}
        imagePullPolicy: {{ .Values.provisioner.imagePullPolicy }}
        {{- if .Values.provisioner.development }}
        command:
          - tini
          - --
        args:
          - /bin/sleep
          - infinity
        {{- else }}
        args:
          - python
          - -m
          - compute_provisioner.provisioner
          - --redis-host
          - {{ template "redis.fullname" . }}-master
          - --namespace
          - {{ .Release.Namespace }}
          - --timeout
          - "{{ .Values.provisioner.timeout }}"
          - --lifetime
          - "{{ .Values.provisioner.lifetime }}"
        {{- end }}
        {{- if not .Values.provisioner.development }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.provisioner.frontendPort }}
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.provisioner.frontendPort }}
          initialDelaySeconds: 40
          periodSeconds: 20
        {{- end }}
        resources: {{ $.Values.provisioner.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        ports:
        - containerPort: {{ .Values.provisioner.frontendPort }}
        - containerPort: {{ .Values.provisioner.backendPort }}
