apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "compute.provisioner.fullname" . }}
  labels:
  {{- include "compute.provisioner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "compute.provisioner.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "compute.provisioner.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "compute.fullname" . }}
      {{- if .Values.provisioner.nodeSelector }}
      nodeSelector: 
      {{ .Values.provisioner.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: provisioner
        image: {{ .Values.provisioner.image }}:{{ .Values.provisioner.imageTag }}
        imagePullPolicy: {{ .Values.provisioner.imagePullPolicy }}
        args:
          - python
          - -m
          - compute_provisioner.provisioner
        env:
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: SERVICE_ACCOUNT_NAME
            value: {{ template "compute.fullname" . }}
          - name: IMAGE_PULL_SECRET
            {{- with first .Values.imagePullSecrets }}
            value: {{ .name }}
            {{- end }}
          - name: LIFETIME
            value: "{{ .Values.provisioner.lifetime }}"
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
        livenessProbe:
          tcpSocket:
            port: 7777
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7777
          initialDelaySeconds: 40
          periodSeconds: 20
        resources: 
        {{ .Values.provisioner.resources | toYaml | nindent 10 }}
        ports:
        - containerPort: 7777
        - containerPort: 7778
