apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "compute.provisioner.fullname" . }}
  labels:
  {{- include "compute.provisioner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "compute.provisioner.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "compute.provisioner.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "compute.fullname" . }}
      {{- if .Values.provisioner.nodeSelector }}
      nodeSelector: 
      {{ .Values.provisioner.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: resource-monitor
        image: {{ .Values.provisioner.image }}:{{ .Values.provisioner.imageTag }}
        imagePullPolicy: {{ .Values.provisioner.imagePullPolicy }}
        args:
          - compute-resource-monitor
          - --redis-host
          - {{ template "redis.fullname" . }}-master
          - --namespace
          - {{ .Release.Namespace }}
          - --timeout
          - {{ .Values.provisioner.timeout | quote }}
        resources: 
        {{ .Values.provisioner.resources | toYaml | nindent 10 }}
      - name: provisioner
        image: {{ .Values.provisioner.image }}:{{ .Values.provisioner.imageTag }}
        imagePullPolicy: {{ .Values.provisioner.imagePullPolicy }}
        args:
          - python
          - -m
          - compute_provisioner.provisioner
          - --redis-host
          - {{ template "redis.fullname" . }}-master
          - --lifetime
          - "{{ .Values.provisioner.lifetime }}"
        env:
          - name: SERVICE_ACCOUNT_NAME
            value: {{ template "compute.fullname" . }}
          - name: IMAGE_PULL_SECRET
            {{- with first .Values.imagePullSecrets }}
            value: {{ .name }}
            {{- end }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: USER_LIMIT_CPU
            value: {{ .Values.userResources.limit.cpu | quote }}
          - name: USER_LIMIT_MEMORY
            value: {{ .Values.userResources.limit.memory | quote }}
          - name: USER_REQUEST_CPU
            value: {{ .Values.userResources.request.cpu | quote }}
          - name: USER_REQUEST_MEMORY
            value: {{ .Values.userResources.request.memory | quote }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.provisioner.frontendPort }}
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.provisioner.frontendPort }}
          initialDelaySeconds: 40
          periodSeconds: 20
        resources: 
        {{ .Values.provisioner.resources | toYaml | nindent 10 }}
        ports:
        - containerPort: {{ .Values.provisioner.frontendPort }}
        - containerPort: {{ .Values.provisioner.backendPort }}
