apiVersion: v1
kind: Service
metadata:
  name: {{ template "compute.provisioner.fullname" . }}
  labels:
  {{- include "compute.provisioner.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "compute.provisioner.matchLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.provisioner.frontendPort }}
    name: frontend
  - port: {{ .Values.provisioner.backendPort }}
    name: backend
