apiVersion: v1
kind: Service
metadata:
  name: {{ template "compute.provisioner.fullname" . }}
  labels:
  {{- include "compute.provisioner.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "compute.provisioner.matchLabels" . | nindent 4 }}
  ports:
  - port: 8888
    name: metrics
  - port: 7777
    name: frontend
  - port: 7778
    name: backend
