kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.dataClaimName }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeBindingMode: {{ .Values.persistence.volumeBindingMode }}
