kind: ServiceAccount
apiVersion: v1
metadata:
  name: compute
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: compute
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
    - ""
    - apps
    - extensions
  resources:
    - namespace
    - serviceaccount
    - role
    - rolebinding
    - resourcequota
    - pods
    - deployments
    - services
    - ingresses
  verbs:
    - list
    - create
    - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: compute
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: compute
roleRef:
  kind: Role
  name: compute
apiGroup: rbac.authorization.k8s.io
