kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "compute.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "compute.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
    - ""
    - apps
    - extensions
  resources:
    - secrets
    - configmaps
    - pods
    - deployments
    - services
    - ingresses
  verbs:
    - get
    - list
    - create
    - patch
    - delete
- apiGroups:
    - ""
    - apps
  resources:
    - pods/logs
  verbs:
    - get
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "compute.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "compute.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "compute.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
