apiVersion: v1
kind: Secret
metadata:
  name: {{ template "compute.fullname" . }}
type: Opaque
data:
  {{- if .Values.wps.secretKey }}
  SECRET_KEY: {{ $.Values.wps.secretKey | b64enc }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  POSTGRES_HOST: {{ include "postgresql.fullname" . | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
