{{- if .Values.thredds.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "compute.thredds.fullname" . }}
  labels:
  {{- include "compute.thredds.labels" . | nindent 4 }}
  {{- if .Values.thredds.ingress.labels }}
  {{ toYaml .Values.thredds.ingress.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.thredds.ingress.annotations }}
  annotations:
  {{ toYaml .Values.thredds.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /threddsCWT/fileServer
            backend:
              serviceName: {{ template "compute.thredds.fullname" . }}
              servicePort: 8080
          - path: /threddsCWT/dodsC
            backend:
              serviceName: {{ template "compute.thredds.fullname" . }}
              servicePort: 8080
{{- end }}
