apiVersion: v1
kind: Service
metadata:
  name: {{ template "compute.thredds.fullname" . }}
  labels:
  {{- include "compute.thredds.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "compute.thredds.matchLabels" . | nindent 4 }}
  ports:
  - port: 8080
