apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "compute.thredds.fullname" . }}
  labels:
  {{- include "compute.thredds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.thredds.replicas }}
  selector:
    matchLabels:
    {{- include "compute.thredds.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "compute.thredds.matchLabels" . | nindent 8 }}
    spec:
      {{- if .Values.thredds.nodeSelector }}
      nodeSelector: 
      {{ .Values.thredds.nodeSelector | toYaml | nindent 10 }}
      {{- end }}
      {{- if .Values.imagePullSecret.create }}
      imagePullSecrets:
        - name: {{ template "compute.fullname" . }}-imagepullsecret
      {{- end }}
      containers:
      - name: thredds
        image: {{ .Values.thredds.image }}:{{ .Values.thredds.imageTag }}
        imagePullPolicy: {{ .Values.thredds.imagePullPolicy }}
        env:
        - name: JAVA_HEAP_INIT
          value: {{ .Values.thredds.heapInit }}
        - name: JAVA_HEAP_MAX
          value: {{ .Values.thredds.heapMax }}
        livenessProbe:
          httpGet:
            path: /threddsCWT/catalog.html
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /threddsCWT/catalog.html
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
        {{ .Values.thredds.resources | toYaml | nindent 10 }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-volume
          mountPath: /data/public
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ or .Values.persistence.existingClaim .Values.persistence.name }}

