apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "compute.wps.fullname" . }}-beat
data:
  CRONTAB_HOUR: {{ .Values.wps.beat.crontabHour | quote }}
  CRONTAB_MINUTE: {{ .Values.wps.beat.crontabMinute | quote }}
  JOB_EXPIRATION: {{ .Values.wps.beat.jobExpiration | quote }}
  JOB_WARN: {{ $.Values.wps.beat.jobWarn | quote }}
  {{- if .Values.wps.secretKey }}
  SECRET_KEY: {{ $.Values.wps.secretKey }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 32 }}
  {{- end }}
  CELERY_BROKER_URL: redis://{{ template "redis.fullname" . }}-master/0
  CELERY_RESULT_BACKEND: redis://{{ template "redis.fullname" . }}-master/0
  POSTGRES_HOST: {{ template "postgresql.fullname" . }}
  PROVISIONER_FRONTEND: {{ template "compute.provisioner.fullname" . }}.{{ $.Release.Namespace }}.svc:{{ $.Values.provisioner.frontendPort }}
