{{- range $.Values.wps.instances }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "compute.wps.fullname" $ }}-{{ .name }}
  labels:
  {{- include "compute.wps.labels" $ | nindent 4 }}
  {{- if .labels }}
  {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if $.Values.wps.ingress.annotations }}
  annotations:
  {{- toYaml $.Values.wps.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
{{- $name := .name }}
{{- $paths := .paths }}
{{- range $paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ template "compute.wps.fullname" $ }}-{{ $name }}
          servicePort: 8000
{{- end }}
---
{{- end }}
