{{- range $.Values.wps.instances }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-wps-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
{{- if .labels }}
{{- toYaml .labels | nindent 4 }}
{{- end }}
{{- if $.Values.wps.ingress.annotations }}
  annotations:
{{- toYaml $.Values.wps.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
{{- $name := .name }}
{{- $paths := .paths }}
{{- range $paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ template "esgf-compute-wps.fullname" $ }}-wps-{{ $name }}
          servicePort: 8000
{{- end }}
---
{{- end }}
