kind: ServiceAccount
apiVersion: v1
metadata:
  name: wps
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wps
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "pods/status", "deployments", "deployments/status", "services", "services/status", "ingresses", "ingresses/status"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wps
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: wps
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: wps
roleRef:
  kind: Role
  name: wps
apiGroup: rbac.authorization.k8s.io
