{{- if $.Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "compute.wps.fullname" $ }}
  labels:
  {{- include "compute.wps.labels" $ | nindent 4 }}
  {{- toYaml $.Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "compute.wps.matchLabels" $ | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 10s
    path: /api/metrics/
{{- end }}
