apiVersion: v1
kind: Service
metadata:
  name: {{ template "compute.wps.fullname" $ }}
  labels:
  {{- include "compute.wps.labels" $ | nindent 4 }}
spec:
  selector:
  {{- include "compute.wps.matchLabels" $ | nindent 4 }}
  ports:
    - port: 8000
      protocol: TCP
