{{- if $.Values.wps.beat.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-wps-beat
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.wps.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: wps-beat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wps-beat
    spec:
      nodeSelector: 
        {{ .Values.wps.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- if $.Values.wps.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.wps.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" . }}-wps-beat
        image: {{ .Values.wps.image }}:{{ .Values.wps.imageTag }}
        imagePullPolicy: {{ .Values.wps.imagePullPolicy }}
        command:
          - tini
          - --
        {{- if .Values.wps.beat.development }}
        args:
          - sleep
          - infinity
        {{- else }}
        args:
          - /bin/bash
        args:
          - celery
          - worker
          - -A
          - compute_wps.tasks
          - -n
          - periodic
          - -l
          - INFO
          - -c
          - "1"
          - -Q
          - periodic
          - --without-gossip
          - --without-mingle
          - -B
        {{- end }}
        resources: {{ $.Values.wps.beat.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        env:
        {{- if $.Values.wps.beat.development }}
        - name: DEV
          value: "1"
        - name: WPS_DEBUG
          value: "1"
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "esgf-compute-wps.fullname" . }}-wps-beat-config
        - secretRef:
            name: {{ template "esgf-compute-wps.fullname" . }}-wps-secret
        volumeMounts:
        - mountPath: /data/public
          name: data-volume
          subPath: public
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.dataClaimName | default "data-pvc" }}
{{- end }}
