apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "compute.wps.fullname" $ }}-external
  labels:
  {{- include "compute.wps.labels" $ | nindent 4 }}
    component/part: external
  {{- toYaml $.Values.wps.ingress.labels | nindent 4 }}
  {{- if $.Values.wps.ingress.annotations }}
  annotations:
  {{- toYaml $.Values.wps.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: {{ template "compute.wps.fullname" $ }}-external
          servicePort: 8000
      - path: /wps
        backend:
          serviceName: {{ template "compute.wps.fullname" $ }}-external
          servicePort: 8000
