apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "esgf-compute-wps.fullname" $ }}-wps-beat-config
data:
  CRONTAB_HOUR: {{ $.Values.wps.beat.crontabHour | quote }}
  CRONTAB_MINUTE: {{ $.Values.wps.beat.crontabMinute | quote }}
  JOB_EXPIRATION: {{ $.Values.wps.beat.jobExpiration | quote }}
  JOB_WARN: {{ $.Values.wps.beat.jobWarn | quote }}
  SECRET_KEY: {{ required "A valid wps.secretKey is required" $.Values.wps.secretKey }}
  CELERY_BROKER_URL: redis://{{ template "redis.fullname" $ }}-master/0
  CELERY_RESULT_BACKEND: redis://{{ template "redis.fullname" $ }}-master/0
  POSTGRES_HOST: {{ template "postgresql.fullname" $ }}
  PROVISIONER_FRONTEND: {{ template "esgf-compute-wps.fullname" $ }}-provisioner.{{ $.Release.Namespace }}.svc:{{ $.Values.provisioner.frontendPort }}
