apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "compute.wps.fullname" . }}
  labels:
  {{- include "compute.wps.labels" . | nindent 4 }}
data:
  django.properties: |
    [auth]
    traefik={{ .Values.wps.auth.traefik.enabled }}
    keycloak={{ .Values.wps.auth.keycloak.enabled }}
    keycloak.url={{ .Values.wps.auth.keycloak.url }}
    keycloak.realm={{ .Values.wps.auth.keycloak.realm }}
    keycloak.client_id={{ .Values.wps.auth.keycloak.clientID }}
    keycloak.client_secret={{ .Values.wps.auth.keycloak.clientSecret }}
    keycloak.reg_access_token={{ .Values.wps.auth.keycloak.regAccessToken }}

    [email]
    host={{ .Values.wps.email.host }}
    port={{ .Values.wps.email.port }}
    user={{ .Values.wps.email.user }}
    password={{ .Values.wps.email.password }}

    [wps]
    title={{ .Values.wps.title }}
    abstract={{ .Values.wps.abstract }}
    keywords={{ .Values.wps.keywords | join "," }}
    provider.name={{ .Values.wps.provider.name }}
    provider.site={{ .Values.wps.provider.site }}
    contact.name={{ .Values.wps.contact.name }}
    contact.position={{ .Values.wps.contact.position }}
    contact.phone={{ .Values.wps.contact.phone }}
    address.delivery={{ .Values.wps.address.delivery }}
    address.city={{ .Values.wps.address.city }}
    address.area={{ .Values.wps.address.area }}
    address.postal={{ .Values.wps.address.postal }}
    address.country={{ .Values.wps.address.country }}
    address.email={{ .Values.wps.address.email }}

    [output]
    dodsc.url={{ .Values.baseUrl }}/threddsCWT/dodsC/public/{filename}

    [server]
    allowed.hosts={{ .Values.wps.allowedHosts | join "," }}
    base.url={{ .Values.baseUrl }}
    provisioner.frontend={{ template "compute.provisioner.frontendService" . }}
