{{- if $.Values.wps.beat.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-wps-beat
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.wps.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: wps-beat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wps-beat
    spec:
      nodeSelector: 
        {{ .Values.wps.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- if $.Values.wps.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.wps.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" . }}-wps-beat
        image: {{ .Values.wps.image }}:{{ .Values.wps.imageTag }}
        imagePullPolicy: {{ .Values.wps.imagePullPolicy }}
        command:
          - tini
          - --
        {{- if .Values.wps.beat.development }}
        args:
          - sleep
          - infinity
        {{- else }}
        args:
          - /bin/bash
        args:
          - celery
          - worker
          - -A
          - compute_wps.tasks
          - -n
          - periodic
          - -l
          - INFO
          - -c
          - "1"
          - -Q
          - periodic
          - --without-gossip
          - --without-mingle
          - -B
        {{- end }}
        resources: {{ $.Values.wps.beat.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        env:
        {{- if $.Values.wps.beat.development }}
        - name: DEV
          value: "1"
        - name: WPS_DEBUG
          value: "1"
        {{- end }}
        - name: CRONTAB_HOUR
          value: {{ .Values.wps.beat.crontabHour | quote }}
        - name: CRONTAB_MINUTE
          value: {{ .Values.wps.beat.crontabMinute | quote }}
        - name: JOB_EXPIRATION
          value: {{ .Values.wps.beat.jobExpiration | quote }}
        - name: JOB_WARN
          value: {{ .Values.wps.beat.jobWarn | quote }}
        - name: SECRET_KEY
          value: {{ required "A valid wps.secretKey is required" .Values.wps.secretKey }}
        - name: CELERY_BROKER_URL
          value: redis://{{ template "redis.fullname" . }}-master/0
        - name: CELERY_RESULT_BACKEND
          value: redis://{{ template "redis.fullname" . }}-master/0
        - name: POSTGRES_HOST
          value: {{ template "postgresql.fullname" . }}
        - name: PROVISIONER_FRONTEND
          value: {{ template "esgf-compute-wps.fullname" . }}-provisioner.{{ $.Release.Namespace }}.svc:{{ $.Values.provisioner.frontendPort }}
        envFrom:
        - secretRef:
            name: {{ template "esgf-compute-wps.fullname" . }}-wps
        volumeMounts:
        - mountPath: /data/public
          name: data-volume
          subPath: public
        {{- if .Values.wps.beat.development }}
        - name: devel-volume
          mountPath: /devel
        {{- end }}
      volumes:
      {{- if .Values.wps.beat.development }}
      - name: devel-volume
        hostPath: 
          path: /opt/cwt/devel
          type: DirectoryOrCreate
      {{- end }}
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.dataClaimName | default "data-pvc" }}
{{- end }}
