{{- range $.Values.wps.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "compute.wps.fullname" $ }}-{{ .name }}
  labels:
  {{- include "compute.wps.labels" $ | nindent 4 }}
    component/part: {{ .name }}
spec:
  selector:
  {{- include "compute.wps.matchLabels" $ | nindent 4 }}
    component/part: {{ .name }}
  ports:
    - port: 8000
      protocol: TCP
      name: metrics
---
{{- end }}
