apiVersion: v2
name: esgf-wps
version: 1.0.1
appVersion: 2.2.0
description: A WPS based compute framework
keywords:
- ESGF
- CWT
- WPS
- compute
home: https://github.com/ESGF/esgf-compute-wps/README.md
sources:
- https://github.com/ESGF/esgf-compute-wps
dependencies:
  - name: postgresql
    version: 10.2.1
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 12.8.3
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus-pushgateway
    version: 1.4.0
    repository: https://charts.helm.sh/stable
  - name: dask-gateway
    version: 0.9.0
    repository: https://dask.org/dask-gateway-helm-repo/
    condition: deploy.daskgateway
  - name: traefik
    version: 9.15.2
    repository: https://helm.traefik.io/traefik
    condition: deploy.traefik
maintainers:
- name: Jason Boutte
  email: boutte3@llnl.gov
engine: gotpl
