dependencies:
  - name: postgresql
    version: 10.2.1
    repository: https://charts.bitnami.com/bitnami
  - name: redis-cluster
    version: 4.2.3
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus-pushgateway
    version: 1.4.0
    repository: https://charts.helm.sh/stable
