dependencies:
  - name: postgresql
    version: 8.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 10.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: traefik
    version: 1.86.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: prometheus
    version: 10.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
