dependencies:
  - name: postgresql
    version: 8.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 9.5.5
    repository: https://kubernetes-charts.storage.googleapis.com/
