# Internal HTTP/TCP load balancer
traefik:
  serviceType: NodePort

  rbac:
    enabled: true

  ssl:
    enabled: true
    enforced: true
    tlsMinVersion: VersionTLS12
    cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    generateTLS: true

  dashboard:
    enabled: false
    domain: ''
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      labels:
        traffic-type: external

  # This traefik instance will only handle ingress objects with these labels
  kubernetes:
    labelSelector: traffic-type=internal

  metrics:
    prometheus:
      enabled: true
      restrictAccess: true

  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 256Mi

    # limits:
    #   cpu: 500m
    #   memory: 512Mi

persistence:
  dataClaimName: compute-data

imagePullSecrets: []
# - name: docker-registry

# User resources
# 
# Per worker allocation is calculate as follows
# worker cpu and memory = (total - scheduler) / instances
userResources:
  # Total resources allocated for a single user
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi

  scheduler:
    resources:
      limits:
        cpu: 1
        memory: 512Mi

  worker:
    nThreads: 2
    instances: 2

# Provisioner
provisioner:
  name: provisioner

  nodeSelector: {}

  image: nimbus16.llnl.gov:8443/default/compute-provisioner
  imageTag: a84476bb
  imagePullPolicy: Always

  frontendPort: 7777
  backendPort: 7778

  timeout: 60
  # Number of seconds that a users dask scheduler and workers will live for (default: 1 hour).
  lifetime: 3600

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 128Mi
    # request:
    #   cpu: 100m
    #   memory: 32Mi

nginx:
  enabled: true

  name: nginx

  replicas: 1

  nodeSelector: {}

  image: nimbus16.llnl.gov:8443/default/compute-webapp
  imageTag: 2d4060a
  imagePullPolicy: Always

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 1Gi
    # requests:
    #   cpu: 100m
    #   memory: 256Mi

  ingress:
    annotations: {}

    labels:
      traffic-type: external

wps:
  name: wps

  nodeSelector: {}

  replicas: 1
  image: nimbus16.llnl.gov:8443/default/compute-wps
  imageTag: a84476bb
  imagePullPolicy: Always

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 200m
    #   memory: 256Mi

  beat:
    enabled: true
    development: false

    # Days until a job expires
    jobExpiration: 30
    # Days before expiration to warn
    jobWarn: 10

    # Configure the celery crontab https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules
    crontabHour: 23
    crontabMinute: 0

    resources: {}
      # limits:
      #   cpu: 500m
      #   memory: 512Mi
      # requests:
      #   cpu: 200m
      #   memory: 256Mi

  # Set to external hostname of cluster
  externalHost: 127.0.0.1
  allowedCIDR: 172.17.0.0/16

  apiUsername: wps_api_username
  apiPassword: wps_api_password

  adminEmail: admin@wps

  # Configure the values that will be used in creating WPS responses
  title: LLNL WPS Server
  abstract: LLNL WPS Compute Service
  keywords:
  - WPS

  provider:
    name: Admin
    site: https://nimbus16.llnl.gov:8443/default

  contact:
    name:
    position:
    phone:

  address:
    delivery:
    city:
    area:
    postal:
    counter:
    email:

  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /api/metrics/
    prometheus.io/port: '8000'

  # OAuth configuration
  oauth:
    client: fake_oauth_client
    secret: fake_oauth_secret

  email:
    host: email@host
    port: 25
    user: ''
    password: ''

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      ingress.kubernetes.io/hsts-max-age: '31536000'
      ingress.kubernetes.io/hsts-include-subdomains: 'true'
      ingress.kubernetes.io/force-hsts: 'true'

  instances:
  - name: external
    enabled: true
    paths:
    - /api
    - /wps
    labels:
      traffic-type: external
  - name: internal
    enabled: true
    paths:
    - /internal_api
    labels:
      traffic-type: internal

celery:
  name: celery

  replicas: 1
  annotations: {}
  nodeSelector: {}

  image: nimbus16.llnl.gov:8443/default/compute-tasks
  imageTag: 7701376c
  imagePullPolicy: Always

  prometheusUrl: prometheus.host

  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi

  backend:
    replicas: 1

    development: false

    redisDB: 3

    trafficType: external

    # Provides mapping for local data
    # mounts and the mapping will be available to a compute backend to translate urls to local data paths.
    localMapping: {}
    #   mounts:
    #     - path: /data
    #       type: hostpath
    #   mapping:
    #     test: /data/test

    resources: {}
      # limits:
      #   cpu: 1
      #   memory: 2Gi
      # requests:
      #   cpu: 500m
      #   memory: 1Gi

  metrics:
    resources: {}
      # limits:
      #   cpu: 1
      #   memory: 2Gi
      # requests:
      #   cpu: 500m
      #   memory: 1Gi


    service:
      port: 8080

      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'

thredds:
  name: thredds

  nodeSelector: {}

  replicas: 1
  image: nimbus16.llnl.gov:8443/default/compute-thredds
  imageTag: a84476bb
  imagePullPolicy: Always

  # Set java parameters for tomcat server
  heapMax: 1g
  heapInit: 512m

  resources: {}
    # limits:
    #   cpu: 1
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 512Mi

  ingress:
    path: /threddsCWT

    annotations: {}

    labels:
      traffic-type: external

postgresql:
  postgresqlUsername: postgres
  postgresqlPassword: abcd1234
  port: 5432

  master:
    nodeSelector: {}

  persistence:
    enabled: false
    existingClaim: postgresql-pvc

  backup:
    enabled: false
    image: bitnami/postgresql
    tag: 10.6.0

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi

redis:
  cluster:
    enabled: false

  usePassword: false

  persistence:
    existingClaim:

  master:
    persistence:
      enabled: false

    resources: {}
      # limits:
      #   cpu: 2
      #   memory: 4Gi
      # requests:
      #   cpu: 2
      #   memory: 4Gi

    nodeSelector: {}

  slave:
    persistence:
      enabled: false

    resources: {}
      # limits:
      #   cpu: 2
      #   memory: 4Gi
      # requests:
      #   cpu: 2
      #   memory: 4Gi

  sentinel:
    persistence:
      enabled: false

    resources: {}
      # limit:
      #   cpu: 500m
      #   memory: 512Mi
      # requests:
      #   cpu: 100m
      #   memory: 256Mi

prometheus:
  enabled: false

twitcher:
  enabled: false

  image: birdhouse/twitcher
  imageTag: latest

  resources: {}

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      ingress.kubernetes.io/hsts-max-age: '31536000'
      ingress.kubernetes.io/hsts-include-subdomains: 'true'
      ingress.kubernetes.io/force-hsts: 'true'
    labels:
      traffic-type: external
