# Disables health/readiness checks and persistent storage.
development: true

persistence:
  dataClaimName: data-dev-pvc

  volumes:
    data-dev:
      storageClassName: slow
      capacity: 100Gi
      path: /p/cscratch/nimbus/wps-dev/data

provisioner:
  image: aims2.llnl.gov/compute-provisioner
  imageTag: c87202cd
  imagePullPolicy: Always
  imagePullSecret: docker-registry

  timeout: 60
  lifetime: 240

nginx:
  image: aims2.llnl.gov/compute-webapp
  imageTag: 9d808f11
  imagePullPolicy: Always
  imagePullSecret: docker-registry

  ingress:
    labels:
      traffic-type: development

wps:
  image: aims2.llnl.gov/compute-wps
  imageTag: 2686ddc2
  imagePullPolicy: Always
  imagePullSecret: docker-registry

  beat:
    enabled: true

    # Days until a job expires
    # 30 Minute expire
    jobExpiration: 0.0208333333333333
    # Days before expiration to warn
    # 15 Minute warn
    jobWarn: 0.0104166666666667

    # Every 5 minutes we'll scan
    crontabHour: '*'
    crontabMinute: '*/5'

  externalHost: 10.5.5.5:8443

  oauth:
    client: dasda
    secret: dadas

  apiUsername: wps_api_user
  apiPassword: changeit

  adminEmail: dasda

  email:
    host: dadagfa

  instances:
  - name: external
    paths:
    - /api
    - /wps
    labels:
      traffic-type: development
  - name: internal
    paths:
    - /internal_api
    labels:
      traffic-type: development

celery:
  image: aims2.llnl.gov/compute-tasks
  imageTag: cb08125e
  imagePullPolicy: Always
  imagePullSecret: docker-registry

  prometheusUrl: adsadas

  backend:
    trafficType: development

thredds:
  image: aims2.llnl.gov/compute-thredds
  imageTag: ec3a3b4e
  imagePullPolicy: Always
  imagePullSecret: docker-registry

  ingress:
    labels:
      traffic-type: development

redis:
  master:
    persistence:
      enabled: false

postgresql:
  postgresqlPassword: abcd1234

  persistence:
    enabled: false

twitcher:
  ingress:
    labels:
      traffic-type: development
