kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: compute-data-dev
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: compute-data-dev
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /p/cscratch/nimbus/data-dev
    type: DirectoryOrCreate
