apiVersion: v1
kind: PersistentVolume
metadata:
  name: compute-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /p/cscratch/nimbus/wps/data
    type: DirectoryOrCreate
