apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  labels:
    environment: dev
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/auth`)
    kind: Rule
    services:
    - name: keycloak
      port: 80
      kind: Service
